language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
script:
  - npm run build && npm run test:prod
after_success:
  - npm run deploy-docs
  - npm run semantic-release
